---
- hosts: all 
  serial: 3
  tasks: 
  - name: 
    debug: 
      msg: | 
        "System total memory: {{ ansible_facts['memtotal_mb'] }} MiB.
        System processor count: {{ ansible_facts['processor_count'] }}"

