---
users: 
  - username: user1 
    groups: webadmin 
  - username: user2
    groups: webadmin 
  - username: user3 
    groups: webadmin 
  - username: user4 
    groups: webadmin 
  - username: user5 
    groups: webadmin 
